#+TITLE: Different Dostoyevsky translations

Welcome! You, like many others (me), have decided to read Dostoyevsky, but do not know which translation to select. Maybe you decide to read The Brothers Karamazov first, since it is after all his magnum opus. Why read the other books when you can read the final one. You go to the Wikipedia page to see the possible choices, and find this:

-  Constance Garnett (1912)
-  Alexandra Kropotkin (1949), revision of Garnett translation
-  David Magarshack (1958)
-  Andrew R. MacAndrew (1970)
-  Julius Katzer (1980, as The Karamazov Brothers)
-  Richard Pevear and Larissa Volokhonsky (1990)
-  David McDuff (1993)
-  Ignat Avsey (1994, as The Karamazov Brothers)
-  Susan McReynolds Oddo (2011), revision of Garnett translation

Oh well. Honestly, I feel like the choice of translation does not alter the experience of reading Dostoyevsky that much, and you should choose whichever one you like. However, choice fatigues you, and so I'd suggest you merely choose between Garnett and Pevear & Volokhonsky for a first read. Dostoyevsky's greatness lies in the fact that mere stylistic changes do not take away even an epsilon amount from the content of his work, unlike certain self-professed aesthetes who find joy in professing their hatred for Dostoyevsky, while managing to produce works that, while undeniably are a pleasure to the senses, manage to leave your soul neither shaken nor stirred.

So how do you choose between Garnett and P&V? Here is a quick rundown of what each one appeals to me for:

* Garnett translation

** Pros:
- It's out of copyright, so it's free on Project Gutenberg
- I like the dated English of this version

** Cons:
- She trudged through stacks of Russian novels and translated them at a blistering pace, and apparently skipped over sentences/paragraphs she did not understand.
- Nabokov and some other Russians say that people do not read Dostoyevsky when they read the books, but merely a bastardized version authored by Garnett.

* P&V translation

** Pros:
- Apparently stick to the rough prose that Dosto used, and do not smooth over the jarring original texts.

** Pro/Con:
- They do this thing where V translates the book literally to English, then P makes it a novel while consulting V.

** Cons:
- Hard to say if the good reviews are marketing or actual fact, since this is the latest translation.

Now to list some articles which argue for either side:

** Pro P&V:
- [[https://www.newyorker.com/magazine/2005/11/07/the-translation-wars][The translation wars]]

** Anti P&V [Usually implies Pro Garnett]:
- [[https://www.commentarymagazine.com/articles/gary-morson/the-pevearsion-of-russian-literature][The Pevearsion of Russian Literature]] [Amazing title btw, you need to read it just for that title]

- [[https://www.firstthings.com/blogs/firstthoughts/2013/01/the-pevearvolokhonsky-hype-machine-and-how-it-could-have-been-stopped-or-at-least-slowed-down][The Pevear/Volokhonsky Hype Machine...]]

** I can't access these, so I'd like it if someone could send them to me.
- [[https://journals.sagepub.com/doi/abs/10.1177/004724419502500322][Review of Avsey's translation]] [Anti-Avsey]

- [[https://www.nytimes.com/1992/04/26/books/raskolnikov-says-the-darndest-things.html][Raskolnikov says the darndest things]]

** General translation comparisons (with extracts)

- [[http://www.patrikbergman.com/2017/07/23/choosing-best-karamazov-translation][Garnett, P&V, MacAndrew, McDuff, Avsey]]
- [[https://www.dartmouth.edu/~karamazo/translations.html][Garnett, P&V, MacAndrew]]
- [[https://theopenmic.co/lost-in-translation-garnett-v-pevearvolokhonsky-part-2][Garnett, P&V]]

My reading order of TBK is as follows:

- Garnett
- Pevear and Volokhnosky
- Andrew MacAndrew
- Ignat Avsey

Other than slight changes, none of these particularly diminished my experience of reading TBK, so I do not think choosing a "wrong" translation is going to negatively affect your view of Dostoyevsky as much as it might affect other authors. If you have other links you'd like me to add, or anything changed in this page at all, feel free to drop me an email! To quote Ivan, /Everything is permitted/, including reading the shittiest translations of TBK. On that note, my translation of TBK comes out soon, never mind that I do not speak a lick of anything harder than A1 Russki.
